name: CI

on:
  push:
    branches:
    - '**'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install g++
        run: sudo apt install -y g++
      - name: check build
        run: source ./compile.sh
