- name: Setup C/C++ Compiler
  # You may pin to the exact commit or the version.
  # uses: rlalik/setup-cpp-compiler@06fe9cc0d7e8c7ea1702d497f0892430c34914ef
  uses: rlalik/setup-cpp-compiler@v1.1
  with:
    # Compiler to install
    compiler: gcc-latest
